config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: :edit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_reader :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest

  has_secure_password

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  before_save :downcase_email
  scope :active, ->{where activated: true}

  class << self
    def digest string
      cost =
        if ActiveModel::SecurePassword.min_cost
          BCrypt::Engine::MIN_COST
        else
          BCrypt::Engine.cost
        end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def current_user? user
    self == user
  end

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"

    return false if digest.blank?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def create_activation_digest
    @activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end

  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  private

  attr_reader :user

  public

  def edit
    @user = User.find_by email: params[:email]
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      active_success
    else
      flash[:danger] = t "users.active_fail"
      redirect_to root_url
    end
  end

  def active_success
    user.activate
    log_in user
    flash[:success] = t "users.active_success"
    redirect_to user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    session = params[:session]
    user = User.find_by email: session[:email].downcase

    if user && user.authenticate(session[:password])
      if user.activated?
        login_success user
      else
        not_activate
      end
    else
      login_fail
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def login_success user
    log_in user
    params[:session][:remember_me] == "1" ? remember(user) : forget(user)
    redirect_back_or user
  end

  def login_fail
    flash.now[:danger] = t "error.login_fail"
    render :new
  end

  def not_activate
    flash[:warning] = t "users.not_active"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new create show)
  before_action :find_user, except: %i(new create index)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  private

  attr_reader :user

  public

  def new
    @user = User.new
  end

  def index
    @users = User.active.paginate page: params[:page]
  end

  def create
    @user = User.new user_params

    if user.save
      user.send_activation_email
      flash[:info] = t "users.create_success"
      redirect_to root_url
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if user.update_attributes user_params
      flash[:success] = t "users.update_success"
      redirect_to user
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    flash[:success] = t "users.destroy_success"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t "users.logged_in"
    redirect_to login_url
  end

  def correct_user
    redirect_to root_url unless user.current_user? current_user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if user
    flash[:danger] = t "users.not_exist_user"
    redirect_to root_path
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "header"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    permanent = cookies.permanent
    permanent.signed[:user_id] = user.id
    permanent[:remember_token] = user.remember_token
  end

  def current_user
    session_id = session[:user_id]
    cookies_id = cookies.signed[:user_id]

    if session_id
      @current_user ||= User.find_by id: session_id
    elsif cookies_id
      authenticate_user cookies_id
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  private

  def authenticate_user cookies_id
    user = User.find_by id: cookies_id

    return unless user && user.authenticated?(:remember,
      cookies[:remember_token])
    log_in user
    @current_user = user
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "partial.footer.content1" %>
      <a href="http://www.railstutorial.org/">
    <%= t "partial.footer.link1" %></a>
    <%= t "partial.footer.content2" %>
      <a href="http://www.michaelhartl.com/"><%= t "partial.footer.link2" %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("partial.footer.about"), about_path %></li>
      <li><%= link_to t("partial.footer.contact"), contact_path %></li>
      <li><%= link_to t("partial.footer.news"),
       href="http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("partial.header.sample"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("partial.header.home"), root_path %></li>
        <li><%= link_to t("partial.header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("partial.header.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle",
              data: {toggle: "dropdown"} do %>
              <%= t "partial.header.account" %><b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("partial.header.profile"), current_user %></li>
              <li><%= link_to t("partial.header.settings"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("partial.header.logout"), logout_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("partial.header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application",
  "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error-explanation">
    <div class="alert alert-danger">
      <%= t "error.the_form" %>
      <%= pluralize @user.errors.count, t("error.error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide:title, t("about.title") %>
<h1><%= t "about.title" %></h1>
<p>
  <%= t "about.content1" %>
  <a href="http://www.railstutorial.org/"><em><%= t "about.link1" %></em></a>
  <%= t "about.content2" %>
  <a href="http://www.railstutorial.org/book"><%= t "about.link2" %></a>
  <%= t "about.content3" %>
  <a href="http://screencasts.railstutorial.org/"><%= t "about.link3" %></a>
  <%= t "about.content4" %>
  <a href="http://rubyonrails.org/"><%= t "about.link4" %></a>.
  <%= t "about.content5" %>
</p>

app/views/static_pages/contact.html.erb
<% provide:title, t("contact.title") %>
<h1><%= t "contact.title" %></h1>
<p>
  <%= t "contact.content" %>
  <a href="http://www.railstutorial.org/contact"><%= t "contact.link" %></a>.
</p>

app/views/static_pages/help.html.erb
<% provide:title, t("help.title") %>
<h1><%= t "help.header" %></h1>
<p>
  <%= t "help.content1" %>
  <a href="http://www.railstutorial.org/help"><%= t "help.link1" %></a>.
  <%= t "help.content2" %>
  <a href="http://www.railstutorial.org/book"><em><%= t "help.link2" %></em>
  <%= t "help.content3" %></a>.
</p>

app/views/static_pages/home.html.erb
<% provide:title, t("home.title") %>
<div class="center jumbotron">
  <h1><%= t "home.header" %></h1>
  <h2>
    <%= t "home.content1" %>
    <a href="http://www.railstutorial.org/"><%= t "home.link" %></a>
    <%= t "home.content2" %>
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
  'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.gravatar_size %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !user.current_user?(current_user) %>
    | <%= link_to t("users.user_delete"), user, method: :delete,
      data: {confirm: t("users.user_confirm")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("edit.title") %>
<% provide :button_text, t("edit.submit") %>
<h1><%= t "edit.header" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("edit.change"),
        "http://gravatar.com/emails", target: "_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("users.list_title") %>
<h1><%= t "users.list_header" %></h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide:title, t("users.title") %>
<% provide :button_text, t("users.create") %>
<h1><%= t "users.title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>